// c64lua compiler seam tests: verify the target:"c64" codegen behaves as the
// SDK expects (c64_ names, color bake, runtime-math divide, no gt.* namespace,
// full P8 draw verbs enabled). These pin the c64 seam so a luacretro update
// can't silently change c64 codegen.
import { test } from "node:test";
import assert from "node:assert";
import { compile } from "../compiler/index.js";
import { P8_TO_C64, nearestColorIndex } from "../compiler/c64_palette.js";

function c(src, opts = {}) {
  const r = compile(src, "t.lua", opts);
  assert.ok(r.ok, (r.diagnostics || []).map((d) => d.message).join("\n"));
  return r.c;
}

test("emits c64_ names + c64_api.h include, void main(void)", () => {
  const out = c(`function _draw() cls(0) end`);
  assert.match(out, /#include "c64_api.h"/);
  assert.match(out, /generated by c64lua/);
  assert.match(out, /void main\(void\)/);
  assert.match(out, /c64_init\(\);/);
  assert.match(out, /c64_cls\(/);
  assert.doesNotMatch(out, /\bgt_/);         // no stray gametank symbols
  assert.doesNotMatch(out, /\bgba_/);
  assert.doesNotMatch(out, /\bmd_/);
});

test("static P8 colors bake to C64 hardware indices", () => {
  // P8 8 (red) -> C64 2 (red); P8 12 (blue) -> C64 14 (light blue)
  const out = c(`function _draw() cls(0) rectfill(0,0,9,9,8) pset(1,1,12) end`);
  assert.match(out, new RegExp(`c64_rectfill\\(0, 0, 9, 9, ${P8_TO_C64[8]}\\)`));
  assert.match(out, new RegExp(`c64_pset\\(1, 1, ${P8_TO_C64[12]}\\)`));
});

test("division/modulo use the runtime fixed helpers (no HW divide on 6510)", () => {
  // %=3 (non-power-of-2) forces the runtime modulo; %=2 would fold to a bitmask.
  const out = c(`local x=1.5\nfunction _update() x=x/3 x%=3 end\nfunction _draw() end`);
  assert.match(out, /c64_fdiv/);              // fixed divide -> runtime helper
  assert.match(out, /c64_ffmod/);             // fixed modulo -> runtime helper
});

test("full P8 draw verb set is enabled (framebuffer target, no refusals)", () => {
  const out = c(`function _draw()
    cls(0) pset(1,2,3) line(0,0,9,9,4) rect(1,1,5,5,6) rectfill(2,2,4,4,7)
    circ(8,8,3,2) circfill(9,9,4,5) print("x",0,0,1) spr(0,10,10)
    local p=pget(1,1) camera(1,1) color(3)
  end`);
  for (const fn of ["c64_pset", "c64_line", "c64_rect", "c64_rectfill",
                    "c64_circ", "c64_circfill", "c64_print", "c64_spr",
                    "c64_pget", "c64_camera", "c64_color"]) {
    assert.match(out, new RegExp(fn.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${fn} should be emitted`);
  }
});

test("the gt.* namespace is rejected on the C64 (no members table)", () => {
  const r = compile(`function _draw() gt.rgb(1,2,3) end`, "t.lua");
  assert.ok(!r.ok);
  assert.match(r.diagnostics.map((d) => d.message).join("\n"), /isn't available on this platform/);
});

test("btn/btnp compile (CIA1 joystick); no zp-fastcall inlining on c64 v1", () => {
  const out = c(`function _update() if btn(0) then end if btnp(4) then end end\nfunction _draw() end`);
  assert.match(out, /c64_btn\(/);
  assert.match(out, /c64_btnp\(/);
});

test("user functions get real C params (no zp-fastcall on c64 v1)", () => {
  const out = c(`function add(a,b) return a+b end\nfunction _update() local z=add(1,2) end\nfunction _draw() end`);
  // real int params, not a (void) zp-fastcall signature
  assert.match(out, /lcl_add\(int /);
});

test("c64 palette: P8_TO_C64 is 16 valid indices; nearestColorIndex is 0-15", () => {
  assert.strictEqual(P8_TO_C64.length, 16);
  for (const v of P8_TO_C64) assert.ok(v >= 0 && v <= 15);
  assert.strictEqual(nearestColorIndex(0, 0, 0), 0);        // black
  assert.strictEqual(nearestColorIndex(255, 255, 255), 1); // white
});
