/* generated by c64lua from main.lua - edit the .lua, not this file */
#include "c64_api.h"

static void lcl__init(void);
static void lcl__draw(void);

static void lcl__init(void)
{
    c64_cls(0);
    c64_circfill(80, 96, 20, 7);
    c64_circfill(72, 90, 3, 12);
    c64_circfill(88, 90, 3, 12);
    { int lcl_i = (-8);
        while ((lcl_i <= 8)) {
            c64_pset((80 + lcl_i), (108 - (int)(c64_fdiv(((long)(lcl_i * lcl_i) << 16), 655360L) >> 16)), 12);
            lcl_i = (lcl_i + 1);
        }
        c64_print("hello c64", 58, 140, 1);
    }
}

static void lcl__draw(void)
{
}

void main(void)
{
    c64_init();
    lcl__init();
    for (;;) {
        c64_update_inputs();
        lcl__draw();
        c64_endframe();
    }
}
