/* generated by c64lua from main.lua - edit the .lua, not this file */
#include "c64_api.h"

static void gtl__init(void);
static void gtl__draw(void);

static void gtl__init(void)
{
    c64_cls(0);
    c64_circfill(80, 96, 20, 7);
    c64_circfill(72, 90, 3, 12);
    c64_circfill(88, 90, 3, 12);
    { int gtl_i = (-8);
        while ((gtl_i <= 8)) {
            c64_pset((80 + gtl_i), (108 - (int)(c64_fdiv(((long)(gtl_i * gtl_i) << 16), 655360L) >> 16)), 12);
            gtl_i = (gtl_i + 1);
        }
        c64_print("hello c64", 58, 140, 1);
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    c64_init();
    gtl__init();
    for (;;) {
        c64_update_inputs();
        gtl__draw();
        c64_endframe();
    }
}
