/* generated by c64lua from main.lua - edit the .lua, not this file */
#include "c64_api.h"

static void lcl_disc(int lcl_cx, int lcl_cy, int lcl_r, int lcl_col);
static void lcl__draw(void);

int lcl_drawn = 0;

static void lcl_disc(int lcl_cx, int lcl_cy, int lcl_r, int lcl_col)
{
    { int lcl_x = lcl_r;
        { int lcl_y = 0;
            { int lcl_d = (1 - lcl_r);
                while (((lcl_x - (lcl_y)) >= 0)) {
                    c64_rectfill((lcl_cx - (lcl_x >> 1)), (lcl_cy + lcl_y), (lcl_cx + (lcl_x >> 1)), (lcl_cy + lcl_y), lcl_col);
                    c64_rectfill((lcl_cx - (lcl_x >> 1)), (lcl_cy - lcl_y), (lcl_cx + (lcl_x >> 1)), (lcl_cy - lcl_y), lcl_col);
                    c64_rectfill((lcl_cx - (lcl_y >> 1)), (lcl_cy + lcl_x), (lcl_cx + (lcl_y >> 1)), (lcl_cy + lcl_x), lcl_col);
                    c64_rectfill((lcl_cx - (lcl_y >> 1)), (lcl_cy - lcl_x), (lcl_cx + (lcl_y >> 1)), (lcl_cy - lcl_x), lcl_col);
                    lcl_y = (lcl_y + 1);
                    if ((lcl_d < 0)) {
                        lcl_d = (lcl_d + ((((lcl_y) << 1)) + 1));
                    } else {
                        lcl_x = (lcl_x - 1);
                        lcl_d = (lcl_d + (((((lcl_y - lcl_x)) << 1)) + 1));
                    }
                }
            }
        }
    }
}

static void lcl__draw(void)
{
    if ((lcl_drawn == 1)) {
        return;
    }
    lcl_drawn = 1;
    c64_cls(0);
    lcl_disc(80, 96, 22, 7);
    lcl_disc(74, 89, 3, 0);
    lcl_disc(86, 89, 3, 0);
    { int lcl_i = (-9);
        while ((lcl_i <= 9)) {
            { int lcl_y = (104 - (int)(c64_fdiv(((long)(lcl_i * lcl_i) << 16), 720896L) >> 16));
                c64_pset((80 + lcl_i), lcl_y, 0);
                c64_pset((80 + lcl_i), (lcl_y + 1), 0);
                lcl_i = (lcl_i + 1);
            }
        }
        c64_print("hello c64", 58, 134, 1);
    }
}

void main(void)
{
    c64_init();
    for (;;) {
        c64_update_inputs();
        lcl__draw();
        c64_endframe();
    }
}
