/* generated by c64lua from main.lua - edit the .lua, not this file */
#include "c64_api.h"

static void lcl__init(void);
static void lcl__draw(void);

static void lcl__init(void)
{
    c64_cls(0);
    c64_print("mathcheck", 50, 8, 1);
    c64_print_int((int)(((long)7 << 15) >> 16), 20, 30, 6);
    c64_print_int((int)(((long)(-9) << 15) >> 16), 20, 42, 6);
    c64_print_int(c64_ifmod(7, 3), 20, 54, 6);
    c64_print_int((int)(c64_fsqrt(3211264L) >> 16), 20, 66, 6);
    c64_print_int((int)((c64_fsin(0L) * 100) >> 16), 20, 84, 5);
    c64_print_int((int)((c64_fsin(16384L /* 0.25 */) * 100) >> 16), 20, 96, 5);
    c64_print_int((int)((c64_fcos(0L) * 100) >> 16), 20, 108, 5);
    c64_print_int((int)((98304L /* 1.5 */ << 2) >> 16), 20, 126, 7);
}

static void lcl__draw(void)
{
}

void main(void)
{
    c64_init();
    lcl__init();
    for (;;) {
        c64_update_inputs();
        lcl__draw();
        c64_endframe();
    }
}
