/* generated by c64lua from main.lua - edit the .lua, not this file */
#include "c64_api.h"

static void lcl__init(void);
static void lcl__draw(void);

unsigned char lcl_ramp[8] = {
    6, 14, 3, 5, 7, 10, 2, 4
};

static void lcl__init(void)
{
    c64_cls(12);
    { int lcl_y = 0;
        while ((lcl_y < 200)) {
            { long lcl_phase = (((long)(int)(((c64_fsin(c64_fdiv(((long)lcl_y << 16), 3932160L)) + 65536L) << 2) >> 16) << 16) + c64_fdiv(((long)lcl_y << 16), 786432L));
                { int lcl_c = lcl_ramp[((int)(lcl_phase >> 16) & 7)];
                    c64_rectfill(0, lcl_y, 159, (lcl_y + 1), lcl_c);
                    lcl_y = (lcl_y + 2);
                }
            }
        }
        c64_print("plasma", 60, 94, 0);
    }
}

static void lcl__draw(void)
{
}

void main(void)
{
    c64_init();
    lcl__init();
    for (;;) {
        c64_update_inputs();
        lcl__draw();
        c64_endframe();
    }
}
