/* generated by c64lua from main.lua - edit the .lua, not this file */
#include "c64_api.h"

static void gtl__init(void);
static void gtl__draw(void);

unsigned char gtl_ramp[8] = {
    6, 14, 3, 5, 7, 10, 2, 4
};

static void gtl__init(void)
{
    c64_cls(12);
    { int gtl_y = 0;
        while ((gtl_y < 200)) {
            { long gtl_phase = (((long)(int)(((c64_fsin(c64_fdiv(((long)gtl_y << 16), 3932160L)) + 65536L) << 2) >> 16) << 16) + c64_fdiv(((long)gtl_y << 16), 786432L));
                { int gtl_c = gtl_ramp[((int)(gtl_phase >> 16) & 7)];
                    c64_rectfill(0, gtl_y, 159, (gtl_y + 1), gtl_c);
                    gtl_y = (gtl_y + 2);
                }
            }
        }
        c64_print("plasma", 60, 94, 0);
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    c64_init();
    gtl__init();
    for (;;) {
        c64_update_inputs();
        gtl__draw();
        c64_endframe();
    }
}
