/* generated by c64lua from main.lua - edit the .lua, not this file */
#include "c64_api.h"

static void gtl__update60(void);
static void gtl__draw(void);

int gtl_x = 76;
int gtl_y = 96;
int gtl_col = 7;

static void gtl__update60(void)
{
    if (c64_btn(0, 0)) {
        gtl_x = (gtl_x - 2);
    }
    if (c64_btn(1, 0)) {
        gtl_x = (gtl_x + 2);
    }
    if (c64_btn(2, 0)) {
        gtl_y = (gtl_y - 2);
    }
    if (c64_btn(3, 0)) {
        gtl_y = (gtl_y + 2);
    }
    if (c64_btnp(4, 0)) {
        gtl_col = (gtl_col + 1);
        if ((gtl_col > 15)) {
            gtl_col = 1;
        }
    }
    if ((gtl_x < 0)) {
        gtl_x = 0;
    }
    if ((gtl_x > 152)) {
        gtl_x = 152;
    }
    if ((gtl_y < 0)) {
        gtl_y = 0;
    }
    if ((gtl_y > 179)) {
        gtl_y = 179;
    }
}

static void gtl__draw(void)
{
    c64_color(gtl_col);
    c64_spr(0, gtl_x, gtl_y, 1, 1, 0 | (0 << 1));
}

void main(void)
{
    c64_init();
    for (;;) {
        c64_update_inputs();
        gtl__update60();
        gtl__draw();
        c64_endframe();
    }
}
