/* generated by c64lua from main.lua - edit the .lua, not this file */
#include "c64_api.h"

static void lcl__update60(void);
static void lcl__draw(void);

int lcl_x = 76;
int lcl_y = 96;
int lcl_col = 7;

static void lcl__update60(void)
{
    if (c64_btn(0, 0)) {
        lcl_x = (lcl_x - 2);
    }
    if (c64_btn(1, 0)) {
        lcl_x = (lcl_x + 2);
    }
    if (c64_btn(2, 0)) {
        lcl_y = (lcl_y - 2);
    }
    if (c64_btn(3, 0)) {
        lcl_y = (lcl_y + 2);
    }
    if (c64_btnp(4, 0)) {
        lcl_col = (lcl_col + 1);
        if ((lcl_col > 15)) {
            lcl_col = 1;
        }
    }
    if ((lcl_x < 0)) {
        lcl_x = 0;
    }
    if ((lcl_x > 152)) {
        lcl_x = 152;
    }
    if ((lcl_y < 0)) {
        lcl_y = 0;
    }
    if ((lcl_y > 179)) {
        lcl_y = 179;
    }
}

static void lcl__draw(void)
{
    c64_color(lcl_col);
    c64_spr(0, lcl_x, lcl_y, 1, 1, 0 | (0 << 1));
}

void main(void)
{
    c64_init();
    for (;;) {
        c64_update_inputs();
        lcl__update60();
        lcl__draw();
        c64_endframe();
    }
}
