/* generated by c64lua from synth-shapes.lua - edit the .lua, not this file */
#include "c64_api.h"

static void lcl__draw(void);

static void lcl__draw(void)
{
    c64_cls(6);
    c64_rectfill(4, 4, 20, 20, 2);
    c64_circfill(64, 64, 10, 7);
    c64_line(0, 0, 159, 199, 1);
    c64_spr(0, 10, 10, 1, 1, 0 | (0 << 1));
    c64_print("hi", 4, 4, 1);
}

void main(void)
{
    c64_init();
    for (;;) {
        c64_update_inputs();
        lcl__draw();
        c64_endframe();
    }
}
