/* generated by c64lua from synth-btn.lua - edit the .lua, not this file */
#include "c64_api.h"

static void gtl__update(void);
static void gtl__draw(void);

static void gtl__update(void)
{
    if (c64_btn(0, 0)) {
    }
    if (c64_btnp(4, 0)) {
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    c64_init();
    c64_p8_fps30();
    for (;;) {
        c64_update_inputs();
        gtl__update();
        gtl__draw();
        c64_endframe();
    }
}
