/* generated by c64lua from synth-fixedmath-num8.lua - edit the .lua, not this file */
#include "c64_api.h"

static void lcl__update(void);
static void lcl__draw(void);

int lcl_x = 0; /* 0 */

static void lcl__update(void)
{
    lcl_x = (lcl_x + 128 /* 0.5 */);
    lcl_x = ((lcl_x) + ((lcl_x) >> 1));
    lcl_x = c64_fdiv(lcl_x, 768);
    lcl_x = (lcl_x & 511);
}

static void lcl__draw(void)
{
}

void main(void)
{
    c64_init();
    c64_p8_fps30();
    for (;;) {
        c64_update_inputs();
        lcl__update();
        lcl__draw();
        c64_endframe();
    }
}
