/* generated by c64lua from synth-array.lua - edit the .lua, not this file */
#include "c64_api.h"

static void gtl__update(void);
static void gtl__draw(void);

int gtl_a[16];
unsigned char gtl_b[8];

static void gtl__update(void)
{
    gtl_a[0] = 5;
    gtl_b[0] = 2;
}

static void gtl__draw(void)
{
}

void main(void)
{
    c64_init();
    c64_p8_fps30();
    for (;;) {
        c64_update_inputs();
        gtl__update();
        gtl__draw();
        c64_endframe();
    }
}
