/* generated by c64lua from synth-fixedmath.lua - edit the .lua, not this file */
#include "c64_api.h"

static void gtl__update(void);
static void gtl__draw(void);

long gtl_x = 0L; /* 0 */

static void gtl__update(void)
{
    gtl_x = (gtl_x + 32768L /* 0.5 */);
    gtl_x = ((gtl_x) + ((gtl_x) >> 1));
    gtl_x = c64_fdiv(gtl_x, 196608L);
    gtl_x = (gtl_x & 131071L);
}

static void gtl__draw(void)
{
}

void main(void)
{
    c64_init();
    c64_p8_fps30();
    for (;;) {
        c64_update_inputs();
        gtl__update();
        gtl__draw();
        c64_endframe();
    }
}
