/* generated by c64lua from synth-fixedmath-num8.lua - edit the .lua, not this file */
#include "c64_api.h"

static void gtl__update(void);
static void gtl__draw(void);

int gtl_x = 0; /* 0 */

static void gtl__update(void)
{
    gtl_x = (gtl_x + 128 /* 0.5 */);
    gtl_x = ((gtl_x) + ((gtl_x) >> 1));
    gtl_x = c64_fdiv(gtl_x, 768);
    gtl_x = (gtl_x & 511);
}

static void gtl__draw(void)
{
}

void main(void)
{
    c64_init();
    c64_p8_fps30();
    for (;;) {
        c64_update_inputs();
        gtl__update();
        gtl__draw();
        c64_endframe();
    }
}
