/* generated by c64lua from synth-func.lua - edit the .lua, not this file */
#include "c64_api.h"

static int lcl_helper(int lcl_x, int lcl_y);
static void lcl__update(void);
static void lcl__draw(void);

static int lcl_helper(int lcl_x, int lcl_y)
{
    return (lcl_x + lcl_y);
}

static void lcl__update(void)
{
    { int lcl_z = (((1) + (2)));
    }
}

static void lcl__draw(void)
{
}

void main(void)
{
    c64_init();
    c64_p8_fps30();
    for (;;) {
        c64_update_inputs();
        lcl__update();
        lcl__draw();
        c64_endframe();
    }
}
