/* generated by c64lua from synth-trig.lua - edit the .lua, not this file */
#include "c64_api.h"

static void gtl__update(void);
static void gtl__draw(void);

static void gtl__update(void)
{
    { long gtl_a = c64_fsin(16384L /* 0.25 */);
        { long gtl_b = c64_fcos(32768L /* 0.5 */);
            { long gtl_c = c64_fatan2(65536L, 131072L);
                { long gtl_d = c64_fsqrt(589824L);
                }
            }
        }
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    c64_init();
    c64_p8_fps30();
    for (;;) {
        c64_update_inputs();
        gtl__update();
        gtl__draw();
        c64_endframe();
    }
}
