/* generated by c64lua from synth-array.lua - edit the .lua, not this file */
#include "c64_api.h"

static void lcl__update(void);
static void lcl__draw(void);

int lcl_a[16];
unsigned char lcl_b[8];

static void lcl__update(void)
{
    lcl_a[0] = 5;
    lcl_b[0] = 2;
}

static void lcl__draw(void)
{
}

void main(void)
{
    c64_init();
    c64_p8_fps30();
    for (;;) {
        c64_update_inputs();
        lcl__update();
        lcl__draw();
        c64_endframe();
    }
}
