/* generated by c64lua from synth-func.lua - edit the .lua, not this file */
#include "c64_api.h"

static int gtl_helper(int gtl_x, int gtl_y);
static void gtl__update(void);
static void gtl__draw(void);

static int gtl_helper(int gtl_x, int gtl_y)
{
    return (gtl_x + gtl_y);
}

static void gtl__update(void)
{
    { int gtl_z = (((1) + (2)));
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    c64_init();
    c64_p8_fps30();
    for (;;) {
        c64_update_inputs();
        gtl__update();
        gtl__draw();
        c64_endframe();
    }
}
